// Pullens Admin — Employee seed data from _seed_employees.csv
// 38 employees, PT001-PT038

import { dobFromId } from '@/lib/utils';

export interface SeedEmployee {
  pt_code: string;
  legacy_code: string;
  full_name: string;
  id_number: string | null;
  dob: string | null;
  gender: string | null;
  race: string | null;
  disability: boolean;
  cell: string | null;
  home_address: string | null;
  occupation: string | null;
  start_date: string | null;
  weekly_wage: number;
  payment_method: string;
  bank_name: string | null;
  bank_acc: string | null;
  bank_branch: string | null;
  bank_type: string | null;
  emergency_name: string | null;
  emergency_rel: string | null;
  emergency_phone: string | null;
  uif_ref: string | null;
  garnishee: number;
  eif_on_file: boolean;
  eif_signed: boolean;
  eif_date: string | null;
  status: string;
  notes: string | null;
}

// Parsed from _seed_employees.csv (24 Apr 2026)
export const SEED_EMPLOYEES: SeedEmployee[] = [
  {
    pt_code: 'PT001', legacy_code: '9002', full_name: 'AARON PHELELANI MKHIZE',
    id_number: '8201135799084', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: '078 683 9180', home_address: 'Thembalihle, Eastwood, 1104', occupation: 'TOMBSTONE FITTER',
    start_date: '2012-09-03', weekly_wage: 2215.97, payment_method: 'eft',
    bank_name: 'Standard Bank', bank_acc: '10064664099', bank_branch: '51001', bank_type: 'savings',
    emergency_name: 'Mercy', emergency_rel: 'Wife', emergency_phone: '078 337 8629',
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: true, eif_date: '2026-02-18',
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT002', legacy_code: '9003', full_name: 'JUNIOR LINDELANI SITHOLE',
    id_number: '8610106911082', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: '074 371 6463', home_address: '03 Edgewood Place', occupation: 'MACHINE OPERATOR',
    start_date: '2018-01-15', weekly_wage: 2561.50, payment_method: 'eft',
    bank_name: 'Nedbank', bank_acc: '1127591959', bank_branch: '19876500', bank_type: 'savings',
    emergency_name: 'Sandile', emergency_rel: 'Brother', emergency_phone: '084 611 1662',
    uif_ref: '2573997/9', garnishee: 300, eif_on_file: true, eif_signed: true, eif_date: '2026-02-17',
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT003', legacy_code: '9004', full_name: 'SIPHO CYPRIAN MTHEMBU',
    id_number: '7801016166088', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: null, home_address: null, occupation: 'TOMBSTONE FITTER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: 'Capitec', bank_acc: '1308098888', bank_branch: '47001000', bank_type: 'savings',
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT004', legacy_code: '9005', full_name: 'WILLIAM NHLANHLA SIHLEZANE',
    id_number: '7810025763082', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: '072 626 3851', home_address: 'Copesville', occupation: 'GENERAL WORKER',
    start_date: '2012-09-03', weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: 'Standard Bank', bank_acc: '10131626351', bank_branch: '51001', bank_type: 'savings',
    emergency_name: 'Gugu', emergency_rel: 'Sister', emergency_phone: '077 386 7706',
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: true, eif_date: '2026-02-18',
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT005', legacy_code: '9006', full_name: 'MUSA BRAIN TIBANA',
    id_number: '8510145893087', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: '081 491 3455', home_address: '36 Scombplaza, Copesville', occupation: 'GENERAL WORKER',
    start_date: '2012-09-03', weekly_wage: 1920.58, payment_method: 'eft',
    bank_name: 'Absa', bank_acc: '9362494609', bank_branch: '63200500', bank_type: 'cheque',
    emergency_name: 'Lunka', emergency_rel: 'Sister', emergency_phone: '076 166 7922',
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: true, eif_date: '2026-02-18',
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT006', legacy_code: '9007', full_name: 'NKULULEKO MIYA',
    id_number: '9209296210089', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: '079 822 9638', home_address: '63 Indes Road, Copesville', occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1744.00, payment_method: 'eft',
    bank_name: 'First National Bank', bank_acc: '62833761663', bank_branch: '250655', bank_type: 'savings',
    emergency_name: 'Cindy', emergency_rel: 'Wife', emergency_phone: '078 016 4573',
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: true, eif_date: '2026-02-18',
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT007', legacy_code: '9008', full_name: 'DAMIEN KOVILAN SEERANGUM',
    id_number: '8008295202084', dob: null, gender: 'Male', race: 'Indian', disability: false,
    cell: null, home_address: '8 Tensingh Road, Belfort, Pietermaritzburg', occupation: 'MECHANIC',
    start_date: '2018-11-12', weekly_wage: 2398.94, payment_method: 'eft',
    bank_name: 'Standard Bank', bank_acc: '10165197429', bank_branch: '51001', bank_type: 'savings',
    emergency_name: 'Marilyn', emergency_rel: 'Sister', emergency_phone: '061 211 4403',
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: true, eif_date: '2026-02-17',
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT008', legacy_code: '9009', full_name: 'MARLYN NAIDOO',
    id_number: '8604230248081', dob: null, gender: 'Female', race: 'Indian', disability: false,
    cell: '061 211 4403', home_address: '8 Tensingh Road, Belfort, Pietermaritzburg', occupation: 'ADMIN',
    start_date: '2016-01-27', weekly_wage: 1451.13, payment_method: 'eft',
    bank_name: 'Standard Bank', bank_acc: '10165190122', bank_branch: '51001', bank_type: 'savings',
    emergency_name: 'Cynthia', emergency_rel: 'Mother', emergency_phone: '061 155 4321 / 033 387 3896',
    uif_ref: '2573997/9', garnishee: 250, eif_on_file: true, eif_signed: true, eif_date: '2026-02-17',
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT009', legacy_code: '9010', full_name: 'THILENTHREN RENGEN',
    id_number: '7305265103081', dob: null, gender: 'Male', race: 'Indian', disability: false,
    cell: '075 472 5974', home_address: '64 Samana Road, Allandale, Pietermaritzburg', occupation: 'MAINTENANCE',
    start_date: '2018-05-01', weekly_wage: 2616.15, payment_method: 'eft',
    bank_name: 'Capitec', bank_acc: '1705575089', bank_branch: '47001000', bank_type: 'savings',
    emergency_name: 'Cheryl / Riya', emergency_rel: 'Wife / Daughter', emergency_phone: '061 421 8350',
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: true, eif_date: '2026-02-17',
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT010', legacy_code: '9025', full_name: 'SIBUSISO MDAWE',
    id_number: '9510206256082', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: null, home_address: null, occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: null, bank_acc: null, bank_branch: null, bank_type: null,
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: 'Banking details still to capture',
  },
  {
    pt_code: 'PT011', legacy_code: '9029', full_name: 'LINDOKUHLE KHANYILE',
    id_number: '8506125554087', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: null, home_address: null, occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: 'Standard Bank', bank_acc: '10072106458', bank_branch: '51001', bank_type: 'savings',
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT012', legacy_code: '9001', full_name: 'NICOLETTE DAVID',
    id_number: '7502150241089', dob: null, gender: 'Female', race: 'Indian', disability: false,
    cell: '084 038 7293', home_address: '64 Samana Road, Allandale, Pietermaritzburg', occupation: 'ADMIN',
    start_date: null, weekly_wage: 1250.00, payment_method: 'eft',
    bank_name: null, bank_acc: null, bank_branch: null, bank_type: null,
    emergency_name: 'Dhiraaj Ismail', emergency_rel: 'Spouse', emergency_phone: '074 212 8006',
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: true, eif_date: '2026-02-17',
    status: 'active', notes: 'ID corrected to 750215 0241 089 per signed EIF. Banking still to capture.',
  },
  {
    pt_code: 'PT013', legacy_code: '9014', full_name: 'ALLI YESSA',
    id_number: 'MA966888', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: '073 616 1763', home_address: null, occupation: 'TOMBSTONE FITTER',
    start_date: null, weekly_wage: 1230.50, payment_method: 'eft',
    bank_name: 'Standard Bank', bank_acc: '10206933620', bank_branch: '51001', bank_type: 'savings',
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: 'Passport holder — verify valid work permit on file',
  },
  {
    pt_code: 'PT014', legacy_code: '9024', full_name: 'ENRIQUE DANTE MUNIEN',
    id_number: '0111265226089', dob: null, gender: 'Male', race: 'Indian', disability: false,
    cell: '081 268 8757', home_address: '64 Samana Road, Allandale, Pietermaritzburg', occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: 'Standard Bank', bank_acc: '10217070610', bank_branch: '00051001', bank_type: 'cheque',
    emergency_name: 'Riya', emergency_rel: 'Wife', emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: true, eif_date: '2026-02-18',
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT015', legacy_code: '9016', full_name: 'CHERYLETTE RENGAN',
    id_number: '7801300216086', dob: null, gender: 'Female', race: 'Indian', disability: false,
    cell: '069 930 9515', home_address: '64 Samana Road, Allandale, Pietermaritzburg', occupation: 'ADMIN',
    start_date: '2019-10-11', weekly_wage: 1337.50, payment_method: 'eft',
    bank_name: 'Standard Bank', bank_acc: '10165149424', bank_branch: '51001', bank_type: 'savings',
    emergency_name: 'Thilen / Riya', emergency_rel: 'Husband / Daughter', emergency_phone: '061 421 8350',
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: true, eif_date: '2026-02-17',
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT016', legacy_code: '9017', full_name: 'SIPHO DION TIBANA',
    id_number: '7807156108087', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: '079 912 9840', home_address: 'Eastwood, 20 Roalbos Road', occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: 'First National Bank', bank_acc: '63062960109', bank_branch: '250655', bank_type: null,
    emergency_name: 'Agnes Tibana', emergency_rel: 'Mother', emergency_phone: '067 562 7784',
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: true, eif_date: '2026-02-23',
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT017', legacy_code: '9018', full_name: 'COSMOS THULASIWE MKHIZE',
    id_number: '8207165757082', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: null, home_address: null, occupation: 'DRIVER/ASSISTANT',
    start_date: '2012-09-03', weekly_wage: 1317.17, payment_method: 'eft',
    bank_name: 'Absa', bank_acc: '9331324562', bank_branch: '63200500', bank_type: 'savings',
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT018', legacy_code: '9019', full_name: 'THABISO JOHANIS MSINDO',
    id_number: '7010315601080', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: '084 000 1656', home_address: 'Thembilihle', occupation: 'POLISHER',
    start_date: '2012-09-03', weekly_wage: 1360.80, payment_method: 'eft',
    bank_name: null, bank_acc: null, bank_branch: null, bank_type: null,
    emergency_name: 'Sithabi', emergency_rel: 'Sister', emergency_phone: '073 678 4586',
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: true, eif_date: '2026-02-17',
    status: 'active', notes: 'Banking details still to capture',
  },
  {
    pt_code: 'PT019', legacy_code: '9020', full_name: 'AYANDA MHLONGO',
    id_number: '9805036118084', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: null, home_address: null, occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: 'First National Bank', bank_acc: '63205475650', bank_branch: '250655', bank_type: null,
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT020', legacy_code: '9021', full_name: 'TIISO LEBATA',
    id_number: '9011066157080', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: null, home_address: null, occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: 'Standard Bank', bank_acc: '10165137159', bank_branch: '51001', bank_type: 'savings',
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT021', legacy_code: '9022', full_name: 'TUMELO VITALIS LEBOFA',
    id_number: 'RC945829', dob: null, gender: null, race: null, disability: false,
    cell: null, home_address: null, occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: null, bank_acc: null, bank_branch: null, bank_type: null,
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: false, eif_signed: false, eif_date: null,
    status: 'active', notes: 'EIF not yet on file — obtain signed copy',
  },
  {
    pt_code: 'PT022', legacy_code: '9023', full_name: 'THABANI XIMBA',
    id_number: null, dob: null, gender: null, race: null, disability: false,
    cell: null, home_address: null, occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: null, bank_acc: null, bank_branch: null, bank_type: null,
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: false, eif_signed: false, eif_date: null,
    status: 'active', notes: 'EIF not yet on file — obtain signed copy',
  },
  {
    pt_code: 'PT023', legacy_code: 'S002', full_name: 'SANELISIWE FAITH NXELE',
    id_number: '64081910314087', dob: null, gender: null, race: null, disability: false,
    cell: null, home_address: null, occupation: 'SALES',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: null, bank_acc: null, bank_branch: null, bank_type: null,
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: false, eif_signed: false, eif_date: null,
    status: 'active', notes: 'EIF not yet on file — obtain signed copy',
  },
  {
    pt_code: 'PT024', legacy_code: 'D002', full_name: 'GUGULETHU CELE',
    id_number: '84021608200080', dob: null, gender: null, race: null, disability: false,
    cell: null, home_address: null, occupation: 'SALES',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: null, bank_acc: null, bank_branch: null, bank_type: null,
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: false, eif_signed: false, eif_date: null,
    status: 'active', notes: 'EIF not yet on file — obtain signed copy',
  },
  {
    pt_code: 'PT025', legacy_code: '9026', full_name: 'SINETHEMBA KWESHUBE',
    id_number: '0111295859081', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: null, home_address: null, occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: 'Standard Bank', bank_acc: '10202571848', bank_branch: '51001', bank_type: 'savings',
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT026', legacy_code: '9027', full_name: 'PHILANI MKHIZE',
    id_number: '8609246518088', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: '076 861 7957', home_address: '61 Triumph Road, Copesville', occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: 'Absa', bank_acc: '9390495576', bank_branch: '63200500', bank_type: 'cheque',
    emergency_name: 'Thulakosi', emergency_rel: 'Brother', emergency_phone: '073 342 0027',
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: true, eif_date: '2026-02-17',
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT027', legacy_code: '9028', full_name: 'MTHOKOZISI MICHAEL MCHUNU',
    id_number: '8302285799088', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: '082 394 1307', home_address: '95 Mason, Copesville', occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: 'Capitec', bank_acc: '1976872683', bank_branch: '47001000', bank_type: 'savings',
    emergency_name: 'Thobani', emergency_rel: 'Brother', emergency_phone: '076 677 4492',
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: true, eif_date: '2026-02-17',
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT028', legacy_code: 'D001', full_name: 'RANDHIR SINGH',
    id_number: '9804205212083', dob: null, gender: 'Male', race: 'Indian', disability: false,
    cell: '074 963 4574', home_address: null, occupation: 'ADMIN',
    start_date: null, weekly_wage: 1820.00, payment_method: 'eft',
    bank_name: 'Standard Bank', bank_acc: '10121040680', bank_branch: '51001', bank_type: 'cheque',
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT029', legacy_code: 'D003', full_name: 'FIKA JABULANI MDLALOSE',
    id_number: '8901126021089', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: null, home_address: null, occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: 'Capitec', bank_acc: '2044946765', bank_branch: '47001000', bank_type: 'savings',
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT030', legacy_code: '9031', full_name: 'SIFISO DENNIS NDLELA',
    id_number: '8212256252084', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: '082 634 1499', home_address: null, occupation: 'DRIVER/ASSISTANT',
    start_date: '2012-09-03', weekly_wage: 1411.33, payment_method: 'eft',
    bank_name: 'Capitec', bank_acc: '2161248029', bank_branch: '47001000', bank_type: 'savings',
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT031', legacy_code: '9036', full_name: 'XOLANI XOLANI',
    id_number: null, dob: null, gender: null, race: null, disability: false,
    cell: null, home_address: null, occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: null, bank_acc: null, bank_branch: null, bank_type: null,
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: false, eif_signed: false, eif_date: null,
    status: 'active', notes: 'EIF not yet on file — obtain signed copy',
  },
  {
    pt_code: 'PT032', legacy_code: 'S001', full_name: 'ZANDILE MCHUNU',
    id_number: '8008261091081', dob: null, gender: 'Female', race: 'African', disability: false,
    cell: null, home_address: null, occupation: 'SALES',
    start_date: null, weekly_wage: 1300.00, payment_method: 'eft',
    bank_name: 'Capitec', bank_acc: '2455598108', bank_branch: '47001000', bank_type: 'savings',
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT033', legacy_code: '9032', full_name: 'SIKHOSIPHI DAVID MTSHALI',
    id_number: '7404085949086', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: '071 171 9094', home_address: 'Mpolweni', occupation: 'DRIVER/ASSISTANT',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: 'Capitec', bank_acc: '1572384164', bank_branch: '47001000', bank_type: 'savings',
    emergency_name: 'Princess', emergency_rel: 'Wife', emergency_phone: '078 178 8883',
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: true, eif_date: '2026-02-18',
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT034', legacy_code: '9034', full_name: 'MLINDENI JOEL LAMULA',
    id_number: '7002245616080', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: null, home_address: null, occupation: 'DRIVER/ASSISTANT',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: 'Absa', bank_acc: '9346856532', bank_branch: '63200500', bank_type: 'savings',
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT035', legacy_code: '9035', full_name: 'MDUDUZI DUNCAN HLELA',
    id_number: '8707015743083', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: null, home_address: null, occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: 'Standard Bank', bank_acc: '10260812690', bank_branch: '51001', bank_type: 'savings',
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: null,
  },
  {
    pt_code: 'PT036', legacy_code: '9015', full_name: 'PHILANI RASTA',
    id_number: null, dob: null, gender: null, race: null, disability: false,
    cell: null, home_address: null, occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: null, bank_acc: null, bank_branch: null, bank_type: null,
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: false, eif_signed: false, eif_date: null,
    status: 'active', notes: 'EIF not yet on file — obtain signed copy',
  },
  {
    pt_code: 'PT037', legacy_code: '9011', full_name: 'SIPHIWE SIBANGANI DUMAKUDE',
    id_number: '7512255524081', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: null, home_address: null, occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: null, bank_acc: null, bank_branch: null, bank_type: null,
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: 'Banking details still to capture',
  },
  {
    pt_code: 'PT038', legacy_code: '9012', full_name: 'NHLANHLA NDLOVU (LUCKY)',
    id_number: '8711065479085', dob: null, gender: 'Male', race: 'African', disability: false,
    cell: null, home_address: null, occupation: 'GENERAL WORKER',
    start_date: null, weekly_wage: 1210.00, payment_method: 'eft',
    bank_name: null, bank_acc: null, bank_branch: null, bank_type: null,
    emergency_name: null, emergency_rel: null, emergency_phone: null,
    uif_ref: '2573997/9', garnishee: 0, eif_on_file: true, eif_signed: false, eif_date: null,
    status: 'active', notes: 'Banking details still to capture',
  },
];

// Enrich DOB from ID numbers
export function getEnrichedEmployees(): SeedEmployee[] {
  return SEED_EMPLOYEES.map((emp) => ({
    ...emp,
    dob: emp.dob || dobFromId(emp.id_number),
  }));
}
